### ISSUE TITLE
Add banner to the LRS homepage to comply with EU directive on cookies.

### ISSUE THREAD

**Issue by claus-zinn** [clarin-eric/LRSwitchboard#11]
The LRS makes use of cookie, and it tracks user behaviour with Piwik. We may need to inform users about this. See [http://alex-d.github.io/Cookies-EU-banner/](http://alex-d.github.io/Cookies-EU-banner/) and [https://github.com/Alex-D/cookies-eu-banner](https://github.com/Alex-D/cookies-eu-banner).

**Comment by dietervu** [comment]
Cookie walls are not a legal requirement, if the cookie is used for the correct functioning of the application (in case LRS). For Piwik we are very privacy-friendly by [respecting](https://www.clarin.eu/content/piwik-background-information) the browser's do-not-track header. So no need at all to add a cookie wall or banner.
