### ISSUE TITLE
Less aggressive caching

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/LRSwitchboard#2]
A suggestion for the currently rather (sometimes problematically) robust caching of the LRS code: maybe try setting some HTML headers to prevent the clients from caching it? See https://stackoverflow.com/q/7413234. 

Or you could use [HTTP headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching) if you have control over those.

Or possibly the best solution: add a query parameter with a unique value to the location of the script file. Maybe at build time the Git revision can be inserted? Or otherwise a checksum of the file itself? For example:
```
<script src="bundle.js?v=b44d38d6d67924bdae6e9bb2d6b46b580d68392b"></script>
```

**Comment by claus-zinn** [comment]
I've added a querying parameter as suggested by twagoo above. This should do the trick.
