### ISSUE TITLE
Possible hardcoded URL path when LRS tries to download a supplied link

### ISSUE THREAD

**Issue by andmor-** [clarin-eric/LRSwitchboard#26]
When I try to use the "Paste link from Dropbox or B2DROP..." input box while running the LRS locally in development mode, I see a "Not found" error when trying to download the file.

After investigating a little, it seems that the error comes from some hardcoded URL path elements on: [util.js#L104](https://github.com/clarin-eric/LRSwitchboard/blob/master/app/back-end/util.js#L104) and [util.js#L106](https://github.com/clarin-eric/LRSwitchboard/blob/master/app/back-end/util.js#L106)

[webpack.config.js#L120](https://github.com/clarin-eric/LRSwitchboard/blob/master/webpack.config.js#L120) as well as multiple places in [nginx.conf](https://github.com/clarin-eric/LRSwitchboard/blob/master/docker/nginx.conf), seem to suffer from a similar problem but here I do not know how relevant this is.

**Comment by claus-zinn** [comment]
The code has been amended to address the issue. Now, the switchboard makes use of an application context, which is determined in the switchboard's entry component 'app'. I have also simplified the code as a reference to CLRS-PATH is no longer necessary in web pack's config. At the same time, the conf. in nguni has been greatly simplified.
