### ISSUE TITLE
main.py code file should be outside the docker folder

### ISSUE THREAD

**Issue by andmor-** [clarin-eric/LRSwitchboard#27]
The file [main.py](https://github.com/clarin-eric/LRSwitchboard/blob/master/docker/app/main.py) currently lives inside the project's "docker" directory. Since this is application code, and not only relevant for docker based deployments, I think this file should be moved to the "app" directory.

This would provide a more clear separation between the application code and the runtime environment components and configuration.

If you like I can submit a pull request for this.

**Comment by claus-zinn** [comment]
The code has now been moved to the main app directory.
