### ISSUE TITLE
Give user a "busy" feedback while detecting language and mimetype

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/LRSwitchboard#40]
Give user a "busy" feedback while detecting language and mimetype

I.e. a spinning wheel or the [bootstrap animated progress bar](https://getbootstrap.com/docs/3.3/components/#progress-animated)

**Comment by claus-zinn** [comment]
The GUI now gives uses a "busy" feedback when detecting mimetype/language characteristics of a given resource.
