### ISSUE TITLE
Show unit on resource size displayed in the validation pane of the resource characteristics

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/LRSwitchboard#44]
Show unit on resource size displayed in the validation pane of the resource characteristics. Currently seems to be showing in bytes, but unit is not specified.

**Comment by claus-zinn** [comment]
Fixed. Now mentions "bytes".

**Comment by dietervu** [comment]
Not urgent, but would it be possible to display Kilobytes instead? This is more familiar to most users.
