### ISSUE TITLE
Remove toggle button from navbar

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/LRSwitchboard#45]
Remove toggle button ("Show All Tools"/"Show All Tools and Web Services") from navbar

**Comment by claus-zinn** [comment]
Done. The toggle button now appears in the Tools View (aka Task Oriented View). Whenever the switch is moved, the tool view is updated automatically (including or excluding web services).
By the way, the "Show All Tools" button in the nav bar (it is still there for the time being) has been renamed to "Tool Inventory" (and its background color greyed).
