### ISSUE TITLE
Change favicon and tab title

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/LRSwitchboard#47]
Style of tab title should be in line with VLO. Favicon should match app icon (see #32)

**Comment by claus-zinn** [comment]
Note that the CLARIN VLO has the CLARIN logo as favicon, not its own logo. Open issue, see https://github.com/clarin-eric/VLO/issues/197

**Comment by claus-zinn** [comment]
Note: For the LRS, it now shows "CLARIN LRS" prefixed with the LRS logo as favicon

**Comment by twagoo** [comment]
Thanks for pointing out this issue with the VLO. Something I just realised: when sourcing the app icon from glyphicons its license may not permit taking an image (bitmap) rendering of it for use e.g. as favicon. We may want to consider using an iconset (font-awesome, google material icons) with a more permissive licence or at least make sure that the icon is part of glyphicons free.

**Comment by claus-zinn** [comment]
I think I am using font-awesome anyway. Just used https://paulferrett.com/fontawesome-favicon/ to convert icon into favicon.

**Comment by twagoo** [comment]
Note that the 'cog' icon (as well as 'cogs') are part of Glyphicon free (CC-BY)

![glyphicons-137-cogwheel](https://user-images.githubusercontent.com/7011396/45828020-e6cdef80-bcf7-11e8-8742-3b84d88c0f52.png)
![glyphicons-138-cogwheels](https://user-images.githubusercontent.com/7011396/45828021-e6cdef80-bcf7-11e8-8ddb-32e0a2521cf9.png)
