### ISSUE TITLE
[Tool] Weblicht chain not functioning for Dutch .doc(x) files

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/LRSwitchboard#5]
When using a dutch .doc(x) file ([example](https://github.com/clarin-eric/LRS-Hackathon/raw/master/samples/resources/doc/hermes-nl.doc)) as input to the LRS, the `WebLicht-Dep-Parsing-NL` option becomes available. However, selecting this leads to an incomplete chain only showing the input document.

Service link: http://tuebingen.weblicht.sfs.uni-tuebingen.de:8080/weblicht/?input=https://github.com/clarin-eric/LRS-Hackathon/raw/master/samples/resources/doc/hermes-nl.doc&lang=nl&analysis=dep-parsing&

I can make a working chain by uploading the same file manually and allowing development tools into the chain. This way I can add `To TCF converter` -> `Tokenizer/Sentences` -> `Alpino Dependency Parser`. Running this seems to hang on the Alpino step though.

**Comment by claus-zinn** [comment]
Ok, seems that the WebLicht predefined workflow chain for Dutch was lost during our branch merging. Will add it asap.

**Comment by claus-zinn** [comment]
The WebLicht chain for Dependency Parsing (Dutch) has now been re-added.
