### ISSUE TITLE
Remove support for web services

### ISSUE THREAD

**Issue by claus-zinn** [clarin-eric/LRSwitchboard#55]
Web services were included in the switchboard primarily to have a higher number of tools accessible to users. With a substantial list of browser-based tools now available, this reason does not longer hold.
Moreover, users wanting to use web services are likely to invoke them directly via curl etc. and do not need the switchboard as a broker for this. 

The removal of web services from the switchboard addresses usability issues. Displaying the result of a web service call (JSON, XML code,etc.) on a tab/webpage is awkward. Also, the switchboard makes available only a single standard invocation configuration for each web service, while experienced users may want to have a better handle on how a given web service is called. 

Moreover, the removal of web services decreases code complexity on the implementation side.

For UI usability, it also simplifies navigation on the switchboard's main page: the options 'show tools', 'show tools and web services', 'show web services') can be removed.

**Comment by claus-zinn** [comment]
The development version of the switchboard at https://weblicht.sfs.uni-tuebingen.de/clrs-dev/#/ has now all web services removed. The freed segmented control has been re-utilized to allow users to choose between tools to filter out tools that require authentication. How do you like it?

**Comment by claus-zinn** [comment]
The latest version of the switchboard stopped its support for web services. The corresponding clrs-rest Registry has all web services entries removed.

**Comment by proycon** [comment]
I checked today and am missing our CLAM based tools? Have they been removed because of this issue? CLAM's hybrid approach delivers tools as a RESTful webservice but with a built-in browser-based frontend (client-side).

**Comment by andmor-** [comment]
@proycon sorry looks like everyone forgot to follow up on this.
Yes all web services have been removed in the scope of this issue. I assume that is why CLAM was removed as well. The current tools registry can be found [here](https://github.com/clarin-eric/LRSwitchboard-rest/blob/master/Registry.js).
Can you provide us with an URL that will instantiate that built-in browser-based UI?

If you think that CLAM tools fall outside the scope of this ticket you can create an issue to re-add them.
