### ISSUE TITLE
Use an email address for helpdesk instead of webform with captcha

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/LRSwitchboard#56]
I would rather use an email address (switchboard@clarin.eu) for the support than a webform, because:

- this does not require the code to be changed and updated frequently
- it is more efficient for the end user: no captcha required, no need to enter your name and email separately, possibility to include screenshots etc

Of course the email address could still be connected to the helpdesk. Same comment goes for the FCS Aggregator help - will file a similar issue there.

**Comment by claus-zinn** [comment]
All references to the CLARIN-D Help Desk and its webform have been removed from the GUI.
