### ISSUE TITLE
Reduce number of components/technologies

### ISSUE THREAD

**Issue by emanueldima** [clarin-eric/LRSwitchboard#67]
We currently have:

1. js frontend
2. node backend
3. nginx proxy
4. java library for detecting mimetypes, fronted by nginx
5. python script for downloading data
6. nextcloud for hosting data

We can consolidate items 2 to 6 into a single java backend with the same functionality. This would make the system easier to work with and easier to deploy.

**Comment by dietervu** [comment]
Addressed with https://github.com/clarin-eric/switchboard release
