### ISSUE TITLE
Clean up tool list before EOSC-hub release

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/LRSwitchboard#69]
Only include openly available or federated login enabled tools

**Comment by andmor-** [comment]
To make things easier to find, here is the current list:
https://github.com/clarin-eric/LRSwitchboard-rest/blob/master/Registry.js

Note: this is part of a different git project.

**Comment by dietervu** [comment]
should be moved to a dev instance:

Apache Stanbol Enhancer (not user friendly enough, now replaced by Distanbol which is more user friendly)

all services with "location": "Nijmegen, The Netherlands (CLAM Webservices)" , because it relies on non-federated loging

**Comment by dietervu** [comment]
also D4Science NER (GATE's Annie) should be moved to development since its output is JSON and refers to the indices of the characters. Not something a non-technical end user could use.

**Comment by claus-zinn** [comment]
Ok. I have added a new slot into the tool's registry:
	"deployment": "production" to mark systems for the production system.
Tools not ready for production are marked with
	"deployment": "development".

I will use an existing environment variable (NODE_ENV) for the switchboard build process to direct the production switchboard to only fetch tools with the deployment status "production".

**Comment by claus-zinn** [comment]
I am closing the issue.

**Comment by andmor-** [comment]
All in all, what is the current way to select "development" or  "production"?
As I understand, set `NODE_ENV` at build time, but to which values?
Also I believe that this is sub-optimal. I would prefer to do this selection at runtime, based on the new `deployment` field.

**Comment by andmor-** [comment]
Since this ticket is rather about cleaning the list (which is still ongoing work), I am reopening it.
