### ISSUE TITLE
UCTO does not support Swedish

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/LRSwitchboard#7]
Trying to process http://clarinws.informatik.uni-leipzig.de:8080/clarinwebservices/sentences/11022/0000-0000-24A4-E/sentencestext/?dataproviderId=8 UCTO is suggested but after logging in it says:

`<clamupload><upload source="?dataproviderId=8" filename="1-004a84d801f0409a8b3633b82bdf2b5ad1.txt" inputtemplate="untokinput" templatelabel="Text document" format="PlainTextFormat"><parameters errors="yes"><StaticParameter id="encoding" name="Encoding" description="The character encoding of the file" value="utf-8"/><ChoiceParameter id="language" name="Language" description="The language this text is in" required="1" error="Selected value was not an option! (sv)"><choice id="en">English</choice><choice id="nl">Dutch</choice><choice id="nl-twitter">Dutch on Twitter</choice><choice id="fr">French</choice><choice id="de">German</choice><choice id="it">Italian</choice><choice id="fy">Frisian</choice></ChoiceParameter><StringParameter id="documentid" name="Document ID" description="Enter a unique identifier for this document (no spaces). Needed only for XML output, will be auto-generated if not specified."/><StringParameter id="author" name="Author" description="The author of the document (optional)"/></parameters></upload></clamupload>`

**Comment by proycon** [comment]
Ah, well spotted! ucto does actually support it but the webservice wasn't up to date with the latest version yet. I have updated it now and will deploy on our production server soonish.

**Comment by proycon** [comment]
Also note: language codes have changed to three-letter iso-639-3 codes now, in line with the latest ucto version (the old ones should work for backward compatibility though)

**Comment by twagoo** [comment]
@proycon if you can let us know as soon as the server has been updated, @claus-zinn can update the metadata in the switchboard.

**Comment by proycon** [comment]
@twagoo @claus-zinn: I have deployed the changes on our production server now.  Also; please ensure you use https as we will probably deprecate http support very soon.

**Comment by proycon** [comment]
(Also use the iso-639-3 codes, the backward compatibility is only in ucto itself, not the webservice, so the iso-639-1 ones don't work now)

**Comment by claus-zinn** [comment]
Ucto is now accepting the missing language options.
