### ISSUE TITLE
Input Analysis labels

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/LRSwitchboard#70]
Labels in the 'Input analysis' area are all lower case, which doesn't look so good.

Also 'mimetype' is probably not the best label. Technically the correct name is 'Media type'. One could argue 'MIME type' is still better understood (I would dare to challenge that) but then it should be two words with upper case for the acronym. 

My suggestion:

* `resource` -> `Resource`
* `mimetype` -> `Media type` (alternatively `MIME type`)
* `language` -> `Language`
* `name` -> `Name` (or `File name`?)
* `size` -> `Size` (or `File size`)

**Comment by claus-zinn** [comment]
Changed the labels. Committed to master.

**Comment by claus-zinn** [comment]
Closing the issue.
