### ISSUE TITLE
Behaviour of 'trash bin' icon for removing input resource

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/LRSwitchboard#71]
The bin icon does not appear fully actionable. Small changes that can be carried out:
* pointer (hand) icon upon hover
* colour change upon hover (although this would not be consistent with rest of UI)
* tooltip or label that explains the behaviour in a few words

**Comment by emanueldima** [comment]
Clicking on the trash bin icon should also clear the text boxes, since it's so close to them (noticed by André).

**Comment by claus-zinn** [comment]
Hovering over the trash bin now shows a pointer (hand) cursor. Also, when clicking on the trashbin, any contents in the URL or text input box are deleted. Checked into master.
