### ISSUE TITLE
Disclaimer/explainer for redistribution of uploaded/provided content

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/LRSwitchboard#72]
Next to the input boxes (see #65) we should have a short line of text that links to a slightly more elaborate bit of text explaining the user that whatever they provide there will be redistributed and will not stay in control of CLARIN. Therefore users should not upload or enter any information that is private, sensitive or has legal restrictions on redistribution. Not sure if we have to address this explicitly, but depending on the chosen tool there is a chance of openly exposing (to external parties) the public download location of the tool.

This (built-in) FAQ can be used to accomodate this.

**Comment by twagoo** [comment]
Suggestion for text on main interface:
![Screenshot 2019-03-18 at 14 10 01](https://user-images.githubusercontent.com/7011396/54532224-8ad2e380-4987-11e9-93bc-af1f2284bb50.png)

**Comment by twagoo** [comment]
Currently in tha FAQ:
>Q: What happens to the research data that is transfered to the switchboard?
>A: The tools that process your resource need to have access to it. For this, your research data is uploaded to a temporary file storage onto a CLARIN-based server for a limited time. The storage server is secured with a password, so access is restricted to authorized personnel only. All uploaded research data is deleted at regular intervals.

I propose to remove this item because it is not 100% accurate. Proposed replacement + additional FAQ item:

> _Q: What happens to the input provided to the switchboard?_
> A: The tools that process your resource need to have access to it. For this, your research data is uploaded to a temporary file storage on a CLARIN-based server for a limited time. The resource is shared on basis of a unique URL that is not publicly listed and hard to guess. This URL is shared with the tool, which may or may not redistribute or store this location. Note that in some cases the URL cannot be passed through the tool over an secure (encrypted) channel. All uploaded research data is deleted at regular intervals. This procedure is carried out for uploaded files, resources provided by reference (pasted URLs and incoming via other services) as well as text inserted manually into the input box on the switchboard web page.
>
> _Q: Can I use the switchboard with resources containing sensitive or private information, or which are subject to restrictions regarding redistribution?_
> CLARIN does not have full control over the shared resource and therefore cannot guarantee its secure transfer, storage or processing. Therefore it is not advised to upload files or enter content that contains sensitive or private information, or is subject to restrictions regarding redistribution.

**Comment by claus-zinn** [comment]
Ok, replaced existing text with text from Twan.

**Comment by twagoo** [comment]
Proposal is to also add a bit of text + link to FAQ (item) to input boxes. My proposal for text is
```
Please note that provided content may be redistributed (_learn more_)
```
but someone might have a better suggestion

**Comment by claus-zinn** [comment]
here's my first take on this, see https://switchboard.clarin.eu/#/
