### ISSUE TITLE
Failure to upload any file after a certain amount of time within session

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/LRSwitchboard#77]
When calling the Switchboard (from the VLO) repeatedly in one session, after a while (under specific circumstances??? perhaps after not uploading for a certain amount of time??), it becomes impossible to process any file. The Switchboard loads but it fails with the generic 'failed to upload' error that also appears when the file is rejected due to mime type or file size.

Creating an issue now to make sure it is documented. André (@andmor-) knows more details, please replace description with better informed one.

**Comment by emanueldima** [comment]
I’m not sure what was causing this problem, but I think it used to happen on the old version of the Switchboard, where the storage was handled by Nextcloud. The current version should not have this problem. Close?
