### ISSUE TITLE
Allow users to use their b2drop.eudat.eu account for intermediate file storage, or the 'drop' of a shared link

### ISSUE THREAD

**Issue by claus-zinn** [clarin-eric/LRSwitchboard#9]
In the standalone version of the LRS, all uploaded files are stored on a MPDCF server in Garching (an experimental version of the LRS makes use of a locally installed Nextcloud instance with a designated user). In the future, LRS users could provide their B2DROP login credentials to the LRS, which would then use the credentials to upload all files to their respective accounts at b2drop.eudat.eu. 

A more generic solution would be the following: users copy a shared link from their cloud storage (Nextcloud, Dropbox) into the LRS interface (new UI element needs to be created complementing the DropArea for files). The LRS would then fetch the file from there (for language and mime type detection) to identify suitable tools.

**Comment by emanueldima** [comment]
We now use our own temporary storage. Close?
